### ISSUE TITLE
Order.java

### ISSUE THREAD

**Issue by Mitziu** [Mitziu/CS-2820-Amazon-Warehouse-B4#1]
Please make sure Order.java compiles. There are some errors.

`class OrderingSystem implements OrderInterface`

It's trying to access an interface that was never created.

`public BeltImpl belt;`

Missing imports

`Belt.pack(orderID);`

Belt was never instantiated. You might've wanted to refer to **belt**

**Comment by Mitziu** [comment]
@maximightiest

**Comment by maximightiest** [comment]
It should be working except for the Inventory stuff now. If you need to comment it out you can it shouldn't break anything but everything compiles correctly except for inventory

**Comment by Mitziu** [comment]
Cool. Thanks
