### ISSUE TITLE
Belttest

### ISSUE THREAD

**Issue by Mitziu** [Mitziu/CS-2820-Amazon-Warehouse-B4#2]
There are some missing imports from the assertStatements such as

`assertEquals("order at picker station", result);`

Also in

`BeltTest test01Belt = new BeltTest();
  String result = test01Belt.onSite_Pick(1, 10);`

you cannot call methods from the test class. You should instantiate belt like

`Belt testBelt = new BeltImpl()`

You culd also create the Belt as an instance variable for the BeltTest class and create a method call setup or something along the lines of that with the @Before annotation.

This could let you reuse the testBelt class without having to create a variable for each test.

@edvega2016uiowa

**Comment by edvega2016uiowa** [comment]
import statements have been included
code has been changed to accommodate needs of other areas interacting with belt
Method : getShippedOrders() allows to give status of orders, method available to all members of Warehouse
